### ISSUE TITLE
test_precedence_template_repo

### ISSUE THREAD

**Issue by HalfDeadPie** [MarekSuchanek/labelord_tests#15]
Dobry den,
chcel by som sa spytat na test test_precedence_template_repo. Z testu mi vyplyva, ze ak pomocou --template-repo zadam repo, ktore je sice prazdne ale ma vyssiu prioritu ako repo v config subore, tak sa neaktualizuje ziadne ine repo, lebo template je prazdny.

Test ocakava 3x GET request ale zaroven aj 'SUMMARY: 2 repo(s) updated successfully', ale neviem prist na to ako tieto dve podmienky naraz splnit. Alebo som niečomu zle pochopil? Rovnaky problem mam v podstate aj pri teste test_update_empty_labels. Dakujem

**Comment by HalfDeadPie** [comment]
v podstate mam rovnaky problem aj pri test_update_empty_labels

**Comment by MarekSuchanek** [comment]
-> https://github.com/cvut/MI-PYT/issues/105
