### ISSUE TITLE
inject_session a reload_config

### ISSUE THREAD

**Issue by HalfDeadPie** [MarekSuchanek/labelord_tests#16]
Dobry den,
chcel som sa spytat co konkretne mam urobit vo funkciach inject_session alebo reload config, pretoze nechcem aby som zadanie pochopil zle.

1. Mam v druhom zadani vyuzivat tu istu session, ktoru vyuzivam v prvom zadani(ako?) alebo mam vytvorit novu session s vlastnou autorizaciou, ako parameter funkcie inject session?

2. Vo funkcii reload_config staci len skontrolovat a pripadne priradit premennu prostredia LABELORD_CONFIG a ak neexistuje, tak nastavit default config config.cfg?

Pri metode POST ma aplikacia aktualizacia aktualizovat vsetky oznacene repos v config subore podla aktualneho eventu. Na aktualizaciu treba vyuzit session a jej metodu POST. Mam tu vyuzit session z funkcie inject_session?

Dakujem

**Comment by MarekSuchanek** [comment]
Dobrý den,

myslím, že jste to částečně pochopil správně:

1.  `inject_session` - aplikace dostane voláním této metody objekt, který má od toho okamžiku používat pro komunikaci s GitHub API (někam si ji uložit a pak při přijetí POST na ní volat metody). V případě spouštění pomocí click podpříkazu `run_server` dostanete session klasicky jako v minulé úloze pomocí kontextu (do webové aplikace si ji předáte sami).
2.  `reload_config` - přečte cestu k souboru z proměnné prostředí `LABELORD_CONFIG` a znovunačte (a zkontroluje) konfiguraci z tohoto souboru.

**Comment by HalfDeadPie** [comment]
OK, Ďakujem za vysvetlenie.
