### ISSUE TITLE
test_hooks.test_label_created

### ISSUE THREAD

**Issue by vanclmil** [MarekSuchanek/labelord_tests#17]
Ahoj,
u testu test_hooks.test_label_created mi to píše tenhle error:
```
betamax.exceptions.BetamaxError: A request was made that could not be handled.

A request was made to https://api.github.com/repos/MarekSuchanek/repocribro/labels that could not be found in test_hooks.test_label_created.
```
I přes to, že tam ten request je, nebo ne?
Díky,
Milan

**Comment by MarekSuchanek** [comment]
Ahoj,

vypadá to, že posíláš na GitHub požadavek, který podle testů nemá proběhnout... Buď na špatnou URI, se špatným tokenem nebo body. 

Marek

**Comment by HalfDeadPie** [comment]
@vanclmil ahoj, v com si mal nakoniec problem ak sa smiem spytat?

**Comment by Wilson194** [comment]
@vanclmil @HalfDeadPie Taky by mě zajímalo, kde byl nakonec problém. Tenhle tip chyby se hrozně špatně hledá, protože to v těch testech není jak kontrolovat....

**Comment by MarekSuchanek** [comment]
Typicky v tomto případě je problém v tom, že posíláte navíc request i pro repozitář, ze kterého již přišla zpráva o vytvoření/změně/smazání. Zkuste se podívat na daný test + konfigurační soubor a pak váš kód, napsat kolik požadavků se pošle a potom se podívejte do dané kazety nebo `session_expectation`. 

Pokud to není ten případ, pak je buď špatně token, chybná URI nebo body (což je divné, pokud to v první úloze máte už udělané správně).

**Comment by vanclmil** [comment]
Jo, zapoměl jsem inicializovat session, díky.
