### ISSUE TITLE
test_no_repos

### ISSUE THREAD

**Issue by vanclmil** [MarekSuchanek/labelord_tests#18]
Ahoj,
jak prosím funguje tenhle test test_bad_config.test_no_repos?
Háže mi to:
```
    def test_no_repos(client_maker, capsys):
        # Test exit code and message for config without repos
        with pytest.raises(SystemExit) as info:
>           client_maker('config_norepos')
E           Failed: DID NOT RAISE <class 'SystemExit'>
```
ale přitom nikde v debugu neodchytím kde to běží (pouze ) `inject_session` a `reload_config`.
Díky,
Milan

**Comment by hroncok** [comment]
Asi tuším, kde je problém. Testy předpokládají, že aplikace zařve s příslušným exit codem už při vytvoření testovacího klienta, tedy že se všechny podstatné věci stanou hned na začátku. Je to proto, že předpokládá využití určitých mechanismů, které zajistí načítání konfigurace ještě před prvním requestem (do aplikace).

Dle zadání je ale  třeba načíst konfiguraci předtím, než provádíme první request (na GitHub), proto je asi v testu chyba (špatný předpoklad).

Pomůže, když test mírně změníš na:

```python
    with pytest.raises(SystemExit) as info:
        client_maker('config_norepos')
        client.get('/')
    ...
```

?

**Comment by MarekSuchanek** [comment]
V `client_maker` se volá `reload_config`, v rámci kterého by měla proběhnout kontrola konfigurace (když explicitně voláme, že chceme načíst konfiguraci). 

V reálném případě stačí konfiguraci kontrolovat stylem _lazy_ (až je to potřeba) nebo před prvním požadavkem ("implicitní" načtení při inicializaci `app`).

**Comment by vanclmil** [comment]
Ok, to bylo ono, díky

**Comment by hroncok** [comment]
Je třeba to v testech opravit.
