### ISSUE TITLE
test_click_run_server

### ISSUE THREAD

**Issue by HalfDeadPie** [MarekSuchanek/labelord_tests#19]
Dobry den,
chcel by som sa spytat na test_click_run_server a aj funkciu run server.

1. Neviem prečo dostavam chybove hlasenie o extra argumente

AssertionError: assert 'Host: 127.66.66.66' in ['Usage: labelord run_server [OPTIONS]', '', 'Error: Got unexpected extra argument (127.66.66.66)', '']

Pri run_server používam options host,port,debug a s tymito parametrami nasledne len volam app.run

2. Vo funkcii run_server si stačí uložiť session do nejakeho lokalneho argumentu a nasledne zavolať app.run s prislušnými argumentami?

Ďakujem

**Comment by MarekSuchanek** [comment]
Když nevidím implementaci (v repu vidím jen starou verzi), tak můžu jenom hádat. Test zkusí toto (lze si to vyzkoušet přímo reálně v příkazové řádce):

```
python labelord.py --config tests_web/fixtures/configs/config_3repos.cfg run_server --debug --host 127.66.66.66 --port 5666
```

Mám podezření, že je v tomto případě `--host` nastavené jako `is_flag=True` a potom tu adresu zatím nebere k přepínači ale jako argument.

V `run_server` si máte nastavit aplikaci `app` (instance třídy `LabelordWeb`) = například si někam uložit `session` z click kontextu a nakonec zavolat `app.run` s příslušnými `debug`, `host` a `port`.

**Comment by HalfDeadPie** [comment]
Problem bol v option --debug, ktoru som nemal ako is_flag=True ale načitaval som ju z premmennej prostredia FLASK_DEBUG. Odpoveď mi pomohla, Ďakujem.
