### ISSUE TITLE
Some stuff is not running under created venv

### ISSUE THREAD

**Issue by MarekSuchanek** [MarekSuchanek/labelord_tests#24]
1. Information about package (via `pkg_resources`)
2. Entrypoint `labelord`

Thanks @AlDrago

**Comment by MarekSuchanek** [comment]
Hopefully fixed with https://github.com/MarekSuchanek/labelord_tests/commit/20df8633a517a14bfefdf659f57a805ea66962f8 (works for me, please try it too)

**Comment by dragomirecky** [comment]
Thanks, it helped. 
(sorry for my late reply)
