### ISSUE TITLE
Could not install from Test PyPI

### ISSUE THREAD

**Issue by BorisLaskov** [MarekSuchanek/labelord_tests#26]
`test_install.py` mi na Ubuntu nefunguje kvuli prikazu 
`pip --extra-index-url https://test.pypi.org/pypi install <package_name>`.

Kdyz to zkousim rucne, dostavam `no such option: --extra-index-url`.

Funguje ale varianta, kdyz davam klicove slovo `install` pred `pip`:
`pip install --extra-index-url https://test.pypi.org/pypi <package_name>`.

Slo by to opravit?

**Comment by hroncok** [comment]
Můžeme to pořadí přehodit, případně by asi šlo ve virtualenvu updatovat pip, aby to fungovalo.

**Comment by hroncok** [comment]
Actually:

```console
$ pip install -U pip
Requirement already up-to-date: pip in ./__env__/lib/python3.6/site-packages
$ pip --extra-index-url https://test.pypi.org/pypi install isholidayXXX

Usage:   
  pip <command> [options]

no such option: --extra-index-url

```

**Comment by MarekSuchanek** [comment]
Jj, opraveno v #28

**Comment by BorisLaskov** [comment]
Vyzkousel jsem to, ted vsechno funguje :) Dekuji
