### ISSUE TITLE
Betamax nenačítá kazety ze spávného souboru

### ISSUE THREAD

**Issue by ghost** [MarekSuchanek/labelord_tests#37]
Mám nassledující problém: 
* Když pouštím CLI, WEB as moje testy separe, funguje to.
* Jakmile je postím naráz, betamax asi nejak nepřenačte cestu ke kazetám a končí na `Cassette must have a valid name and may not be None`.
* Prodebugoval jsem se až k tomu, že si opravdu sahá na kazety ve složce `tests_cli` i když chce načíst kazetu třeba `test_bad_config.test_no_labels`.
* Dočasně jsem to vyřešil tak, že jsem ty WEB kazety nakopíroval do mezi CLI kazety, ale pořádně spravit se mi to nepovedlo.

Struktura testů:
```
tests
├── tests_cli
│   ├── fixtures
│   ├── __pycache__
│   ├── test_list_labels.py
│   ├── test_list_repos.py
│   ├── test_run_basic.py
│   ├── test_run_prints.py
│   ├── test_run_replace.py
│   ├── test_run_tricky.py
│   └── test_run_update.py
├── tests_my
│   └── test_result_printer.py
└── tests_web
    ├── conftest.py
    ├── fixtures
    ├── test_bad_config.py
    ├── test_basic.py
    ├── test_hooks.py
    ├── test_index.py
    ├── test_usage_click.py
    └── test_usage_flask.py
```

Pouštím to: `python setup.py test` Více v: https://github.com/Achse/labelord

Díky - určo to bude nějaká blbost, ale nedokázal jsem to prokopnou.

**Comment by hroncok** [comment]
Ve skutečnosti máš `conftest.py` i ve složce `tests_cli`. Bijí se mezi sebou, jeden se najde dřív a nastaví cestu ke kazetám. Pokud chceš, aby to fungovalo dobře, měl bys mít jen jeden.

**Comment by ghost** [comment]
Díky, jsem mazal koukám z tree `__pychache__` a smazal jsem i to důležitý. Vyřešil jsem to nakonec tak že jsem ty testy uplně máznul a pouštím je uplně externě.
