### ISSUE TITLE
Hundred repos bug?

### ISSUE THREAD

**Issue by kulikjak** [MarekSuchanek/labelord_tests#4]
Mám podezření, že v testu na více než 100 repositářů je chyba v testovacích datech a tedy padá *assert* v testu. 

Podle testu se očekává výstup ve tvaru `MarekSuchanek/repo{}`, ale ačkoliv v testovacích datech jsou repositáře na adresách `MarekSuchanek/repo`, tak hodnoty `login name` a `owner` jsou *cvut* a *MI-PYT* a v testu to spadne.

**Comment by MarekSuchanek** [comment]
Data do kazet jsem generoval skriptem a čekal jsem, že všichni použijí rovnou položku `full_name` (kvalifikované jméno), což je moje chyba - omlouvám se a kazety upravím.

Díky za issue!

**Comment by MarekSuchanek** [comment]
Upraveno... https://github.com/MarekSuchanek/labelord_tests/commit/d43102be59eee6c40e12d5e59d303f972142bec9

**Comment by kulikjak** [comment]
Děkuji - já jsem zase přehlédl, že něco jako `full_name` existuje.
