### ISSUE TITLE
Testy na prázdné inputy v updatu

### ISSUE THREAD

**Issue by popekmic** [MarekSuchanek/labelord_tests#5]
V zadání stojí : "Pokud nejsou repozitáře specifikované ani jedním způsobem, pak program na standardní chybový výstup vypíše No repositories specification has been found, skončí s kódem 7."

Ale test test_update_empty_repos, kterej používá config bez repozitářu a nedává --all-repos kontroluje že program skončí správně s 0 a vypíše že updatoval 0 repozitářú.

To samé pro test test_update_empty_label . Dle zadání : "Pokud nejsou štítky specifikované ani jedním způsobem, pak program na standardní chybový výstup vypíše No labels specification has been found, skončí s kódem 6." 

Ale test zkouší, jestli šli dva get requesty, exit code 0 a výpis na dva updatnuté repository.

**Comment by MarekSuchanek** [comment]
Je rozdíl mezi prázdným seznamem repozitářů/štítků a žádným seznamem repozitářů/štítků (v konfiguračním souboru chybí celá sekce). V zadání je v obou případech napsáno:
> Seznam může být prázdný.

Rozdíl je znát z konfiguračních souborů (například `norepos`/`emptyrepos`): https://github.com/MarekSuchanek/labelord_tests/tree/master/tests/fixtures/configs

**Comment by popekmic** [comment]
Jo, ok už to chápu. Možná by nebylo od věci dopsat do zadání že i prázdný seznam je validní vstup, to že seznam muže být prázdný jsem práve pochopil jako case, kterej se musí ošetřit a vyhodit chybu :D.

**Comment by MarekSuchanek** [comment]
OK, upraveno v https://github.com/cvut/MI-PYT/commit/413195f2aecdd747f8a80e81e437557965a329cb
