### ISSUE TITLE
Isolated=True při testování CL argumentů

### ISSUE THREAD

**Issue by muckpetr** [MarekSuchanek/labelord_tests#6]
Rád bych se zeptal, co přesně znamená parametr isolated u testů výpisu helpu a verze, konkrétně mám problém s exit codem.
- v případě isolated = False mi všechny testy dopadnou správně
- v případě isolated = True help příkazy volané na podpříkazech (např list_labels --help) vrací chybu chybějícího tokenu.

Token načítám v souhrnném příkazu CLI (stejně, jako např configurační soubor), bude tedy zřejmě problém v tom, že při hodnotě True proběhne ještě celý souhrnný příkaz, zatímco při False ne. Jednoduché testy z command line ale vždy vrací správně exit code 0.

Je tohle špatná cesta a měl by se skutečně načítat token až v každém podpříkazu nebo existuje i jiný způsob? Pokoušel jsem se experimentovat s click.help_option bez větších úspěchů.

**Comment by hroncok** [comment]
> Rád bych se zeptal, co přesně znamená parametr isolated u testů výpisu helpu a verze, konkrétně mám problém s exit codem.

Parameter `isolated` [přepíná](https://github.com/MarekSuchanek/labelord_tests/blob/9f609c9f296bd36d7bceab07465eb06e1c62b468/tests/conftest.py#L58), jestli se použije [File System Isolation](http://click.pocoo.org/5/testing/#file-system-isolation) - jestli se testy pouští v prázdné složce.

> v případě isolated = False mi všechny testy dopadnou správně

Máš ve složce, ze které testy pouštíš, konfigurační soubor `config.cfg`? Pokud ano, při spuštění testů aplikace tento soubor použije (dle zadání) a `--help` funguje.

> v případě isolated = True help příkazy volané na podpříkazech (např list_labels --help) vrací chybu chybějícího tokenu.

Tady už se testované příkazy pouštějí z prázdné složky, ve které takový konfigurační soubor není. Bum, fail.

(Jen hádám, tvůj kód jsem neviděl, nemám přístupy do žádného tvého repozitáře.)

> Token načítám v souhrnném příkazu CLI (stejně, jako např configurační soubor), bude tedy zřejmě problém v tom, že při hodnotě True proběhne ještě celý souhrnný příkaz, zatímco při False ne. Jednoduché testy z command line ale vždy vrací správně exit code 0.

> Je tohle špatná cesta a měl by se skutečně načítat token až v každém podpříkazu nebo existuje i jiný způsob? Pokoušel jsem se experimentovat s click.help_option bez větších úspěchů.

Tohle už jsme řešili s @145k0v v soukromé issue. Lepší řešení, než mít funkci na kontrolu tokenu a tu funkci volat v podpříkazech (případně si na to udělat vlastní dekorátor), neznám (to ale neznamená, že neexistuje). Provádění kontroly (přítomnosti) tokenu v hlavní group funkci má za následek nefunkční `--help` podpříkazů.

**Comment by hroncok** [comment]
Než začnu rozbíjet click na prvočinitele, nebo zakládat issues, nevíš @encukou náhodou, jak zjistit z group commandu, že subcommand se zavolal s `--help`?

**Comment by encukou** [comment]
Z hlavy ne :(
