### ISSUE TITLE
Nedeterminičnost testu?

### ISSUE THREAD

**Issue by kulikjak** [MarekSuchanek/labelord_tests#7]
Je možné, že testy ne úplně přesně kontrolují requesty? *Update_with_errors* test mi občas projde a občas ne v závislosti na tom, v jakém pořadí posílám na server requesty (pokud je pošlu abecedně dle jména labelů, tak je vše v pohodě, pokud se ale přehází, tak ne). 

Vždy první projde a další dva ne bez ohledu na to, co jsem poslal...

dík

**Comment by MarekSuchanek** [comment]
To je zvláštní... prověřím

**Comment by hroncok** [comment]
@kulikjak Na jaké verzi Pythonu?

**Comment by kulikjak** [comment]
@hroncok Pokud se nepletu tak na 3.5.2.

**Comment by hroncok** [comment]
Myslím, že by to mohlo souviset s tím, že pořadí položek ve slovníku je nedeterministické, což se nám na 3.6 neděje (změnila se vnitřní implementace slovníku, která ma zajímavý side effect, že věci ve slovníku zachovávají za určitých podmínek pořadí). Zkusíš testy z větve `experimental-matchers` https://github.com/MarekSuchanek/labelord_tests/pull/10?

Poznámka pro nás: Zkoušet testy na 3.5.

**Comment by kulikjak** [comment]
Tak skutečně na 3.6.3 už test projde vždycky. Ty druhé testy zkusím - jen teď už musím na cvičení...

**Comment by kulikjak** [comment]
V nových testech mi to padá skoro na půlce testů na špatných requestech, ale to může být moje chyba...

**Comment by hroncok** [comment]
Ok, koukneme na to na cvičení. Díky za info
